### ISSUE TITLE
Update check does not happen reliably when app returns to foreground

### ISSUE THREAD

**Issue by dvdsgl** [Microsoft/mobile-center-sdk-ios#601] opened 2017-06-08 17:16 UTC
Simple test apps automatically check for updates when returning to the foreground. My more complex app (which uses Firebase, perhaps this is causing interference) does not display the update available dialog when returning to foreground–it only does so on launch.

**Comment by TroubleMakerBen** [comment] 2017-06-13 15:55
Hi @dvdsgl,

> I'd like to check for updates when my app returns to the foreground, not only when it is launched. 

The SDK actually checks for updates every time the ap comes into the foreground, so it's not just happening when it's launched for the first time.

> How can I trigger a manual update check?

There is no API for this.

🖖
Benny

**Comment by dvdsgl** [comment] 2017-06-13 16:03
I only ask because this is not the behavior I see. I have to relaunch my app to see the update prompt.

**Comment by TroubleMakerBen** [comment] 2017-06-13 23:00
@dvdsgl We looked at the code again and it *should* work but as it apparently doesn't work, we need to look into it again. Apologies for my initial reply.

**Comment by TroubleMakerBen** [comment] 2017-06-15 16:45
@dvdsgl We're about to release 0.10.0 and I can't repro this at all. =( The [attached video](https://github.com/Microsoft/mobile-center-sdk-ios/files/1078333/In-app-update-when-backgrounding.mov.zip) shows the behavior on iOS 8.3, 10.0, 10.2 and 10.3.
Can you please get in touch via Slack? I'd love to have a look at the device logs. Thx!

**Comment by dvdsgl** [comment] 2017-06-15 23:32
My automatic setup (swizzling) failed because I am using Firebase. Are there other overrides I need to implement on my AppDelegate maybe?

**Comment by jaelim-ms** [comment] 2017-06-15 23:54
For Distribute, openUrl is the only one. If you have the same issue on Push, there are couple of methods you have to do manually .

**Comment by clpolet** [comment] 2017-06-16 00:01
@dvdsgl Are you referencing the issue you reported last time about `openURL`? This one was caused by an issue in the Info.plist file, duplicate declaration of the custom scheme.

**Comment by dvdsgl** [comment] 2017-06-16 19:37
Confirming that the update dialog appears as expected when returning the app the foreground, using a sample app.

**Comment by guperrot** [comment] 2017-07-28 23:14
@dvdsgl do you still have issues?

**Comment by guperrot** [comment] 2017-08-07 18:44
No news here, closing.

**Closed by guperrot** 2017-08-07 18:44 UTC
Labels: support

**Comment by dvdsgl** [comment] 2017-08-07 21:31
Sorry! Haven't had time to retry. I will reopen if this is still an issue.
