### ISSUE TITLE
Error loading file

### ISSUE THREAD

**Issue by pvinis** [Microsoft/mobile-center-sdk-ios#535] opened 2017-05-08 13:35 UTC
I added this sdk to a react native app, by just adding the npm packages and then in cocoapods, like the recommended way says. I call the generate crash on the native part of the application, and it crashes correctly. Then next time it opens, i get an error like `[MobileCenterCrashes] ERROR: -[MSWrapperExceptionManager loadWrapperExceptionDataWithUUIDString:]/179 Error loading file /var/mobile/Containers/Data/Application/C6EEA96E-122D-4A1F-B78C-CE8C506CFD24/Documents/wrapper_exceptions/A2FCB855-6C78-499A-A55B-85F7C438CC51.ms: The file “A2FCB855-6C78-499A-A55B-85F7C438CC51.ms” couldn’t be opened because there is no such file.`
What is the problem? It is a bug?

**Comment by jaelim-ms** [comment] 2017-05-08 16:30
Looks the issue is related to React Native SDK. Can you use https://github.com/Microsoft/mobile-center-sdk-react-native and ask them the issue?

**Comment by TroubleMakerBen** [comment] 2017-05-08 17:07
Hey @pvinis,

I'm closing this and created  an issue on the RN SDK's Github ([#32](https://github.com/Microsoft/mobile-center-sdk-react-native/issues/32)), so we can track the issue where it belongs. I know we haven't been very responsive over there, this is gonna change from now on.

Best,
Benny

**Comment by pvinis** [comment] 2017-05-08 17:08
thank you

**Closed by TroubleMakerBen** 2017-05-08 17:07 UTC
